GET http://localhost:3000/benedikt/chat/7

################################################################

DELETE  http://localhost:3000/benedikt/chat/7

################################################################

POST http://localhost:3000/benedikt/chat
Content-Type: application/json

{
  "months": ["Jan", "Feb", "Mar", "Apr", "May"],
  "m_count": [8, 7, 6, 5, 3],
  "m_total": 29,
  "m_img": 0,
  "m_video": 0,
  "m_audio": 0,
  "m_data": 0
}

################################################################
POST http://localhost:3000/benedikt/person
Content-Type: application/json

{
  "name": "Herbert",
  "pm_count": [8,7,6,5,3],
  "chat_id": 6
}

################################################################

GET http://localhost:3000/benedikt/chat/people/6